# docker-compose.yml

services:
  nginx:
    image: jonasal/nginx-certbot:5.2.1
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=rossiblack@duck.com
      - RENEWAL_INTERVAL=7d # default is 8d, can use 60m or 1h or 1d
      - STAGING=1
      - DEBUG=1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - mongo
      - mongo-express
      - skkapisvc
      - skkuisvc
      - svc1
      - svc2
      - berryuisvc
      - shikokuuisvc
      - minorsvc

  svc1:
    image: nginxdemos/hello:latest
    container_name: ctnsvc1
    ports:
      - 8099:80

  svc2:
    image: ealen/echo-server:0.9.2
    container_name: ctnsvc2
    ports:
      - 8098:80

  mongo:
    image: mongo:8.0-rc
    restart: always
    volumes:
      - ./mongodata:/data/db
    ports:
      - 38018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: hello99_password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: hello99_password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: hello99_password
      ME_CONFIG_MONGODB_URL: mongodb://admin:hello99_password@mongo:27017/
    depends_on:
      - mongo

  skkapisvc:
    image: tom4dock/shikoku-platform-api:0.0.1-src
    restart: always
    volumes:
      - ./info_images:/app/app/static/info_images
      - ../image/backend/app:/app/app
    ports:
      - 31244:80
    environment:
      MONGODB_URI: mongodb://admin:hello99_password@mongo:27017/
      DOCS_URL: /docs
      OPENAPI_URL: /openapi.json
      LOG_LEVEL: debug
    depends_on:
      - mongo

  # 前端docker部署
  skkuisvc:
    image: tom4dock/skkui:latest
    restart: always
    volumes:
      - ../image/frontend:/app
    command: yarn start
    ports:
      - 17281:3000
    env_file:
      - .env
    depends_on:
      - skkapisvc

  # 前端docker部署
  berryuisvc:
    image: tom4dock/berryui:latest
    restart: always
    volumes:
      - ../image/frontend2:/app
    command: yarn preview
    ports:
      - 17282:5050
    env_file:
      - .env
    depends_on:
      - skkapisvc

  # 前端docker部署
  shikokuuisvc:
    image: tom4dock/shikokuui:latest
    restart: always
    volumes:
      - ../image/frontend3:/app
    # command: pnpm preview
    command: pnpm start
    ports:
      - 17283:3000
    env_file:
      - .env
    depends_on:
      - skkapisvc

  # minor service
  minorsvc:
    image: nginx:alpine
    container_name: ctnsvc4
    ports:
      - 8097:80
    volumes:
      - ../image/frontend4:/usr/share/nginx/html
    restart: always
