services:

  # helloworld2:
  #   image: crccheck/hello-world
  #   container_name: helloworld-2

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email rossiblack@duck.com -d xyz.shikoku.co.jp --agree-tos
  nginx:
    image: nginx:1.25.5
    container_name: jdp-nginx-dev-1
    restart: unless-stopped
    environment:
      - TZ=Asia/Taipei
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - 3-3-joint-defense-platform-api
      - jointdefense-ui-dev

  mongo:
    image: mongo:8.0-rc
    restart: always
    volumes:
      - ./mongodata:/data/db
    ports:
      - 38018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: hello_password
    container_name: jdp-mongo-1

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8089:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: hello_password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: hello_password
      ME_CONFIG_MONGODB_URL: mongodb://admin:hello_password@jdp-mongo-1:27017/
    depends_on:
      - mongo
    container_name: jdp-mongo-express-1

  3-3-joint-defense-platform-api:
    # image: ${CONTAINER_REGISTRY}/itri/3-3-joint-defense-platform-api:0.0.1-src
    image: itri/3-3-joint-defense-platform-api:0.0.3-src
    restart: always
    volumes:
      - ./info_images:/app/app/static/info_images
      - ../image/backend/app:/app/app
    ports:
      - 31244:80
    environment:
      MONGODB_URI: mongodb://admin:hello_password@jdp-mongo-1:27017/
      DOCS_URL: /docs
      OPENAPI_URL: /openapi.json
      LOG_LEVEL: debug
    depends_on:
      - mongo
    container_name: jdp-api-dev-1

  jointdefense-ui-dev:
    # image: ${CONTAINER_REGISTRY}/itri/3-3-fraud-prevention-platform-ui:0.0.0
    image: jointdefense-ui-dev:latest
    restart: always
    volumes:
      - ../image/frontend:/app
    ports:
      - 17281:3000
    env_file:
      - .env
    command: yarn start
    container_name: jdp-ui-dev-1
